### ISSUE TITLE
Implement JWT authentication

### ISSUE THREAD

**Issue by mahnouman** [tamiat/backend#13]
Reference:
https://tutorialedge.net/golang/authenticating-golang-rest-api-with-jwts/

**Comment by RahmaYasser** [comment]
done

**Comment by odetolakehinde** [comment]
@RahmaYasser please link the pull request to this issue. So it can get closed immediately the pull request is merged.

**Comment by RahmaYasser** [comment]
I think I don't have permissions to link pr to an issue
